server:
  port: 8085

spring:
  application:
    name: transaction-ms
  datasource:
    url: jdbc:mysql://localhost:3306/transaction_db?useSSL=false&serverTimezone=UTC
    username: root
    password: anaroot5
    jpa:
      hibernate:
        ddl-auto: update
      database-platform: org.hibernate.dialect.MySQL8Dialect
      show-sql: true
